# Generated by Django 3.2.25 on 2026-04-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_restaurant_cuisine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('japanese', 'Japanese'), ('thai', 'Thai'), ('greek', 'Greek')], max_length=100),
        ),
    ]
