# Generated by Django 3.2.25 on 2026-04-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20260415_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
